# Версия docker-compose
version: '3.7'
# Список наших сервисов (контейнеров)
services:
  nginx:
    # используем последний стабильный образ nginx
    image: nginx:latest
    # маршрутизируем порты
    ports:
      - "82:80"
    # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
    volumes:
      - ./docker/hosts:/etc/nginx/conf.d
      - ./:/var/www
      - ./docker/logs:/var/log/nginx
    # nginx должен общаться с php контейнером
    links:
      - php_chat
    networks:
      - internal
    depends_on:
      - php_chat
      - mariadb
  php_chat:
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build: ./docker/images/php
    container_name: php_chat
    ports:
      - "9859:9859"
    # этот образ будет общаться с mysql
    links:
      - mariadb
    # монтируем директорию с проектами
    volumes:
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.210.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
      TZ: Europe/Moscow
    networks:
      - internal
  mariadb:
    image: mariadb:latest
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    # задаем пароль для root пользователя
    environment:
      MYSQL_ROOT_PASSWORD: aladen
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
      MYSQL_DATABASE: social_web
      TZ: Europe/Moscow
    networks:
      - internal
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.210.0/28
